// <auto-generated />
namespace RecipeApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initalDbSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalDbSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201407070418033_initalDbSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
